name: Install Ubuntu in VirtualBox

on: [push]

jobs:
  install-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up VirtualBox
      run: sudo apt-get install -y virtualbox

    - name: Give execute permission to the script
      run: chmod +x install_ubuntu_virtualbox.sh

    - name: Run installation script
      run: ./install_ubuntu_virtualbox.sh
